### ISSUE TITLE
Could not create PKCS12 from /etc/openunison/unisonKeyStore.p12

### ISSUE THREAD

**Issue by greg-swift-yohana** [OpenUnison/openunison-k8s#134]
Following through the [ArgoCD instructions](https://openunison.github.io/deployauth/#deploying-with-argocd), after creating the secret using uniquely generated secrets. I generated them as 100 char, random alphanumeric, no special characters. I base64 encoded before putting into the k8s secret by copy pasting the block from the documentation and replacing the existing base64 secrets.

Once this was in place and everything started creating, things immediately stopped with the openunison-orchestra pods going into crashloop backoff with the attached pod output.

[openunison-orchestra-pod.log](https://github.com/user-attachments/files/18011781/openunison-orchestra-pod.log)

**Comment by mlbiam** [comment]
Take a look at the operator logs.  The `orchestra` `Secret` is generated by the operator.  If there aren't any logs besides watches, you can force the operator to make an update by adding an annotation to the `openunison`, it should be named `orchestra`

**Comment by greg-swift-yohana** [comment]
[operator.log](https://github.com/user-attachments/files/18013388/operator.log)

Aside from the startup lines its all watching

**Comment by greg-swift-yohana** [comment]
Okay.. in case in all my back and forth setting this up yesterday i triggered the issue in the first place with out of order something or other I decided to start clean with the final setup i had.

Updated logs.

Of note, orchestra pods (why is it maintaining 2 active replica sets?) both still have the same original error:

```
[2024-12-04 22:35:21,533][main] WARN  OpenUnisonOnUndertow - Could not create PKCS12 from /etc/openunison/unisonKeyStore.p12, falling back to JCEKS
java.io.IOException: keystore password was incorrect
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2097) ~[?:?]
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:228) ~[?:?]
	at java.base/java.security.KeyStore.load(KeyStore.java:1500) ~[?:?]
	at com.tremolosecurity.openunison.undertow.OpenUnisonOnUndertow.setupTlsListener(OpenUnisonOnUndertow.java:534) [openunison-on-undertow-1.0.41.jar:?]
	at com.tremolosecurity.openunison.undertow.OpenUnisonOnUndertow.main(OpenUnisonOnUndertow.java:284) [openunison-on-undertow-1.0.41.jar:?]
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	... 5 more
Exception in thread "main" java.io.IOException: Invalid keystore format
	at java.base/com.sun.crypto.provider.JceKeyStore.engineLoad(JceKeyStore.java:727)
	at java.base/java.security.KeyStore.load(KeyStore.java:1500)
	at com.tremolosecurity.openunison.undertow.OpenUnisonOnUndertow.setupTlsListener(OpenUnisonOnUndertow.java:540)
	at com.tremolosecurity.openunison.undertow.OpenUnisonOnUndertow.main(OpenUnisonOnUndertow.java:284)
```

Different error in the operator keys around this:

```
Problem patching secret - 201 /
```

The whole secrets.json is about 490k, so doesn't seem to be hitting the 1MiB per secret limit o_O 

So I extracted the json object and tried running it myself:

```✗ kc apply -n openunison -f secret.json                                                                                                                                        
The Secret "orchestra" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

Which is weird, cause there is almost nothing in annotations?

```
{
  "uid": "392dccf7-59a3-4cb1-9eb7-dd0734b179c3",
  "managedFields": [
    {
      "apiVersion": "v1",
      "manager": "Java-http-client",
      "fieldsV1": {
        "f:data": {
          "f:openunison.yaml": {},
          "f:unisonKeyStore.p12": {},
          "f:cacerts.jks": {},
          "f:ou.env": {},
          ".": {}
        },
        "f:metadata": {
          "f:annotations": {
            "f:tremolo.io/last_updated": {},
            ".": {}
          }
        },
        "f:type": {}
      },
      "time": "2024-12-04T22:32:00Z",
      "operation": "Update",
      "fieldsType": "FieldsV1"
    }
  ],
  "resourceVersion": "1538945",
  "name": "orchestra",
  "namespace": "openunison",
  "creationTimestamp": "2024-12-04T22:32:00Z",
  "annotations": {
    "tremolo.io/last_updated": "2024-12-04T22:32:00.321Z"
  }
}
```

So quick trip to teh googles....

https://github.com/argoproj/argo-cd/issues/820 <-- the data objects in the last-applied stuff is the problem

And I'm betting this is _all_ an issue because I used long passwords?

**Comment by greg-swift-yohana** [comment]
I was gonna go update the argo setup to allow this but then realized this is internal to openunison, ya?

**Comment by greg-swift-yohana** [comment]
Took the extracted secret object from the log, removed some of the metadata (so that kc replace wouldn't complain) and used `kc replace -f secret.json` to apply it.

It applied, and this showed up in the operator logs:

```
Watching https://kubernetes.default.svc/apis/openunison.tremolo.io/v6/namespaces/openunison/openunisons?watch=true&timeoutSeconds=10&allowWatchBookmarks=true&resourceVersion=1555816
Type: MODIFIED
Resource Version: 1555897
Resource 1555897 changed, processing
Processing key : unison-tls
Secret namespace : openunison
Secret name : unison-tls
Secret exists
Adding existing secret that should never be replaced if exists to keystore
Storing keypair into keystore
Processing key : unison-ca
Secret namespace : openunison
Secret name : ou-tls-certificate
Secret exists
Adding existing secret that should never be replaced if exists to keystore
Storing just the certificate for the existing Secret
Processing key : unison-saml2-rp-sig
Secret namespace : openunison
Secret name : unison-saml2-rp-sig
Secret exists
Adding existing secret that should never be replaced if exists to keystore
Storing keypair into keystore
Processing key : remote-k8s-idp-sig
Secret namespace : openunison
Secret name : remote-k8s-idp-sig
Secret exists
Adding existing secret that should never be replaced if exists to keystore
Storing keypair into keystore
Loading static Secrets from /api/v1/namespaces/openunison/secrets/orchestra-static-keys
Checking static key session-unison
Keeping unchanged
Checking static key lastmile-oidc
Keeping unchanged
Writing Secret to /api/v1/namespaces/openunison/secrets/orchestra-static-keys
Problem patching secret - 201 / <json object>
```

So it tried to update it again and failed again.

But also the orchestra pods pulling the updated secret still have the same issue.

I'm also a touch confused because after I replaced the `secret/orchestra` and operator tried to update it again the live secrets are now different than what operator _or_ I are loading into place o_O

**Comment by greg-swift-yohana** [comment]
wait.. they might not be different? ignore that last sentance... they were just in a diff order and i was relying too heavily on the diff tool 😮‍💨

**Comment by mlbiam** [comment]
If it's generating the secret without errors, in your `orchestra-secrets-source`, did you use `echo -n` to make sure that the password doesn't have an extra `\n`?

**Comment by greg-swift-yohana** [comment]
UGH... yes that was the issue
