### ISSUE TITLE
Helm installation of orchestra fails on inability to find the "orchestra" secret

### ISSUE THREAD

**Issue by cocagne** [OpenUnison/openunison-k8s#23]
I'm following through the installation instructions at https://openunison.github.io/deployauth/ and am running into a problem with the helm deployment of orchestra with the command " helm install orchestra tremolo/orchestra --namespace openunison -f values.yml". The helm installation succeeds but the "openunison-orchestra" POD continually enters the CrashLoopBackoff state. A kubectl describe pod on this pod shows: 

MountVolume.SetUp failed for volume "secret-volume" : secret "orchestra" not found

The orchestra secret is created as part of the helm install and listing out the secrets in the openunison namespace shows that the "orchestra" secret does indeed exist. I've tried deleting and recreating the secret but the POD still fails to run. Any assistance in troubleshooting this error would be appreciated. (Kube version 1.22.5)

**Comment by mlbiam** [comment]
> The orchestra secret is created as part of the helm install 

not exactly.  The `orchestra` `Secret` is created by the operator.  When the helm chart installs the `openunison-orchestra` `Deployment` it will generate the `MountVolume.SetUp failed for volume "secret-volume" : secret "orchestra" not found` error until the `Secret` is generated.

If the `Secret` exists, but the pods won't launch i'd try deleting the `Pod` or scaling the `Deployment` to 0 then to 1.

**Comment by mlbiam** [comment]
> org.xml.sax.SAXParseException; lineNumber: 180; columnNumber: 36; An invalid XML character (Unicode: 0x4) 

Which mechanism are you using for authentication?  This generally means that one of the values in `orchestra-secrets-source` contains an invalid XML character.  In this instance, 0x4 is a control character `\d`

**Comment by cocagne** [comment]
I'm using GitHub authentication. I pasted in a copy of the client_id but manual inspection doesn't show any hidden characters. I'll try starting with a fresh copy of the values.yml file and avoid using copy/paste in case that's how the errant control character is somehow getting into the system.

**Comment by mlbiam** [comment]
Look in the `Secret`, not the values.yaml.  Probably in the `GITHUB_SECRET_ID`, might need to request a new secret id from github

**Comment by cocagne** [comment]
Hmm. I double-checked the `GITHUB_SECRET_ID` and it's just a base64 encoded hexadecimal string. It shouldn't be possible an embedded control character to be in there, should it?
