### ISSUE TITLE
Utf-8 Character Problem in group names

### ISSUE THREAD

**Issue by burakkaracay** [OpenUnison/openunison-k8s#37]
Hello,
Group names in our Active Directory has some Turkish characters.
So when the users from these groups logged in to the Login Portal, they cannot grant their permissions. And they see their roles with missing characters. (? instead of Turkish chars)
For example;
```
CN=şöyle böyle,CN=Users,DC=ent2k12,DC=domain,DC=com
```
seems like
```
CN=??yle b?yle,CN=Users,DC=ent2k12,DC=domain,DC=com
```
Is there any char settings for the application?

Thank you.

**Comment by mlbiam** [comment]
I think I have this figured out:

1. Delete all users `kubectl delete users --all -n openunison`
2. Update `image` to `docker.io/tremolosecurity/betas:ou-k8s-1.0.30` and redeploy the `orchestra` chart

**Comment by burakkaracay** [comment]
Thank you very much.
I deleted all the users and I updated the image in openunison-orchestra deployment. But It didn't work out. 
```
# kubectl -n openunison edit deployments.apps openunison-orchestra
# kubectl -n openunison describe pod openunison-orchestra-85f5675b58-6vtrd | grep Image: | grep -v istio
    Image:          docker.io/tremolosecurity/betas:ou-k8s-1.0.30
# kubectl -n openunison describe pod openunison-operator-58d5458bc4-hdw8r | grep Image: | grep -v istio
    Image:         docker.io/tremolosecurity/openunison-k8s-operator:latest
# kubectl -n openunison describe pod ouhtml-orchestra-login-portal-55ccc56cc6-tlzwr | grep Image: | grep -v istio
    Image:          docker.io/tremolosecurity/openunison-k8s-html
```

**Comment by mlbiam** [comment]
Can you give me the yaml of the user object that isn't working as expected?

```
kubectl get users -o yaml -n openunison
```

Thanks

**Comment by burakkaracay** [comment]
I shared the user at the attachment.
```
[users.txt](https://github.com/OpenUnison/openunison-k8s/files/8521417/users.txt)
```

**Comment by mlbiam** [comment]
the `HTTP PATCH` wasn't using `utf-8`.  Got that fixed.  delete your orchestra pod and it will pull in the latest version of the `docker.io/tremolosecurity/betas:ou-k8s-1.0.30` image:

`kubectl delete pods -l app=openunison-orchestra -n openunison`

**Comment by mlbiam** [comment]
`However Turkish characters are still missing in the user's roles page in OpenUnison GUI.`

Noticed that too, at least we got the functional part working.  investigating the display issue

**Comment by mlbiam** [comment]
Once more, delete your orchestra pod and it will pull in the latest version of the `docker.io/tremolosecurity/betas:ou-k8s-1.0.30` image:

`kubectl delete pods -l app=openunison-orchestra -n openunison`

Should get it displaying properly

**Comment by burakkaracay** [comment]
It's displaying properly right now. Thank you for your quick solution.

**Comment by mlbiam** [comment]
should be published some time next week
