### ISSUE TITLE
Customize k8s context name

### ISSUE THREAD

**Issue by alenhodzic85** [OpenUnison/openunison-k8s#38]
Hi,
Can we somehow customize k8s context name so we can have it different for different clusters. Now it is just `kubernetes`.

`export TMP_CERT=$(mktemp) && echo -e "" > $TMP_CERT && kubectl config set-cluster kubernetes --server=...`

**Comment by mlbiam** [comment]
Yes, set `k8s_cluster_name` in your values.yaml

**Comment by alenhodzic85** [comment]
Yes that is it. Thanks again.
