### ISSUE TITLE
update certificate endpoint api version

### ISSUE THREAD

**Issue by lucakuendig** [OpenUnison/openunison-k8s#46]
When using the option certs.use_k8s_cm: true the operator fails to create the cert for the kubernetes-dashboard because it still calls the v1beta1 endpoint forcertificates.k8s.io

```
Approving CSR
Problem calling '/apis/certificates.k8s.io/v1beta1/certificatesigningrequests/kubernetes-dashboard.kubernetes-dashboard.svc/approval' - 404
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}

Retrieving signed certificate
Problem calling '/apis/certificates.k8s.io/v1beta1/certificatesigningrequests/kubernetes-dashboard.kubernetes-dashboard.svc' - 404
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}
```

could you please update the operator so it uses the v1 endpoint or at least tries both?

**Comment by mlbiam** [comment]
We were actually thinking of removing that feature. The reason we originally built it was to make it easier to integrate with ingress controllers, but it turned out to not matter (and doesn't work for hosted clusters like eks). What was your goal by using certs signed by the kubernetes CA?

**Comment by lucakuendig** [comment]
I had no specific goal in mind. I just noticed while trying out openunison and thought you might wanted to know. If you plan on removing it anyways that is fine with me.

**Comment by mlbiam** [comment]
I updated the name of this issue to reflect that we need to remove this feature since it's never used and as pointed out the API its using is out of date.  I'll keep this open until we officially remove it.

**Comment by mlbiam** [comment]
the latest version of our operator has removed this feature, closing
