### ISSUE TITLE
Keep me signed in after browser close

### ISSUE THREAD

**Issue by alenhodzic85** [OpenUnison/openunison-k8s#54]
Hi,
We are using Azure as IdP. When the browser is closed and reopened, you need to login again. Not great user experience. Is this created by design? Other services don't have this issues like gitlab or jenkins.

There are some exceptions like Opera browser on Windows.

Kind regards,

**Comment by alenhodzic85** [comment]
Yes, that's right.

**Comment by mlbiam** [comment]
Sorry for the delay, was on vacation.

> Yes, that's right.

We don't enforce a re-authentication, that's managed by your identity provider (AzureAD in this case).  I think there's a setting on AzureAD that lets you stay logged in after restarting the browser.

**Comment by alenhodzic85** [comment]
Hey sorry, I was on vacation too.

Yes, there is an option in Azure and it is already enabled:

**Azure Active Directory > Company branding > Configure > Advanced settings section > Show option to remain signed in > YES**

![image](https://user-images.githubusercontent.com/54853176/187214469-3bc3188a-b0c0-4721-b2cd-c365bac39c26.png)

And this on client side

![image](https://user-images.githubusercontent.com/54853176/187216528-fbc247e1-5ab3-4ceb-b852-0eebec8aa7b1.png)


Is it possible somehow app isn't trying to use persistent cookie stored on the disk, because other applications don't have this problem (gitlab, jenkins...)

**Comment by alenhodzic85** [comment]
Hi [mlbiam](https://github.com/mlbiam), have you managed to see my previous message?
